db=postgres
health-enabled=true
features=client-secret-rotation,admin-fine-grained-authz

spi-email-sender-provider=govuknotify
spi-email-sender-govuknotify-enabled=true

spi-events-listener-event-publisher-enabled=true
spi-events-listener-jboss-logging-enabled=true
