name: TDR Tag and pre deploy Auth Server
on:
  push:
    branches:
      - master
jobs:
  pre-deploy:
    uses: nationalarchives/tdr-github-actions/.github/workflows/ecs_build.yml@main
    with:
      repo-name: tdr-auth-server
      image-name: auth-server
      java-version: '21'
      build-command: |
        npm install
        npm run build-theme
        wget --header "Authorization: token $GITHUB_TOKEN" https://raw.githubusercontent.com/nationalarchives/tdr-configurations/master/keycloak/tdr-realm-export.json
        sbt assemblyPackageDependency assembly
    secrets:
      MANAGEMENT_ACCOUNT: ${{ secrets.MANAGEMENT_ACCOUNT }}
      WORKFLOW_PAT: ${{ secrets.WORKFLOW_PAT }}
      WIZ_CLIENT_ID: ${{ secrets.WIZ_CLIENT_ID }}
      WIZ_CLIENT_SECRET: ${{ secrets.WIZ_CLIENT_SECRET }}
      WIZ_PROJECT_ID: ${{ secrets.WIZ_PROJECT_TDR }}
  deploy:
    needs: pre-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - run: gh workflow run deploy.yml -f environment=intg -f to-deploy=${{ needs.pre-deploy.outputs.next-version }}
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_PAT }}
